slack:
  bot-token: bot-token
  signing-secret: signing-secret
  client-id: client-id
  client-secret: client-secret
  redirect-uri: redirect-url
  scopes: "chat:write,chat:write.customize,channels:read,groups:read,commands,users:read"

token:
  access-key: thisIsA32ByteAccessTokenKeyForHS
  refresh-key: thisIsA32ByteRefreshTokenKeyForH
  encryption-key: thisIsA32ByteEncryptionKeyForAES
  issuer: local-issuer
  access-expired-seconds: 3600
  refresh-expired-seconds: 259200
  access-expired-millis-seconds: 3600000
  refresh-expired-millis-seconds: 259200000

access-link:
  key-secret: access-link-secret
